<!DOCTYPE html>
<html>
<head>
<title>A Frankenstein Atlas Home</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="frankenstein_home.css">
</head>
<body>


<!-- Page content -->
<div class="w3-content w3-padding" style="max-width:1564px">

<!-- About Section -->
<div class="w3-container w3-padding-32" id="about">
    <h1 class="w3-border-bottom w3-border-light-grey w3-padding-16">About</h1>
    <p>A Frankenstein Atlas explores Mary Shelley's novel Frankenstein from a spatial perspective. Inspired by research and theoretical approaches in literary mapping and historical geography, A Frankenstein Atlas provides scholars and students with a platform to study and experiment with Shelley's text.</p> 

    <p>This website provides users with access to the maps, gazetteer, pedagogical approach, and writing generated by the Frankenstein Atlas team. It also provides a link to the datasets and schemas underlying the atlas. Teachers are encouraged to create new maps as well as use, improve, and expand these data sets in their courses by creating Github branches. New work can then be integrated into the main repository and, through collaboration, this project can continue to expand. 
    </p>
 
    <h1 class="w3-border-bottom w3-border-light-grey w3-padding-16">Contributors</h1>
    <p>A Frankenstein Atlas was originally created as a class project for the course, <a href="https://ageofmachines.wordpress.com/">Machines and the Age of Invention</a>, taught by Jason M. Kelly during Spring 2018. Using <i>Frankenstein</i> as its key text, the course explored the history of science and medical ethics during the 18th and 19th centuries. Topics discussed in class included grave robbing, dissection, gender, and human consciousness. Students in the course worked collaboratively to develop the schema for our analysis as well as coding the text for integration and analysis using GIS. Students who participated in this project included Jessie Cortesi, Dalton Gackle, Patrick Hanlon, Kyla Lewis, Blake Miller, and Sam Opsahl. The schema, data sets, and website is edited by Jason M. Kelly.</p> 
    
    <p>This project was originally developed as part of the course <a href="https://ageofmachines.wordpress.com/">Machines and the Age of Invention</a> and was part of IUPUI’s commitment to <a href="https://indianahumanities.org/programs/one-state-one-story-frankenstein">One State / One Story: Frankenstein</a>, an Indiana Humanities program made possible in part by a major grant from the National Endowment for the Humanities. Any views, findings, conclusions or recommendations expressed in this program do not necessarily represent those of the National Endowment for the Humanities.
    </p>

    <h1 class="w3-border-bottom w3-border-light-grey w3-padding-16">Using the Atlas</h1>
    <p>Mary Shelley’s (née Godwin) Frankenstein is a profoundly geographical text. The novel opens with an epistolary exchange between St. Petersburg and London and, from there, it takes readers on a peregrination back-and-forth across Northern Europe and the circumpolar north. The book’s characters expand the text’s geographic boundaries by imagining lands and peoples in the Americas, Asia, and the Pacific. The ways in which Shelley describes these places is essential not only to the narrative but also to our understanding of the novel’s fundamental themes. Given this rich geographical framework, Frankenstein offers teachers a valuable tool with which to explore the historical, geographical, and literary worlds of the late eighteenth and early nineteenth centuries.</p> 

    <p>An open access project created at IUPUI in 2017-2018 in response to the 200th anniversary of the book’s publication, A Frankenstein Atlas is deeply influenced by the theories and practices associated with the spatial humanities—especially literary mapping, deep mapping, and humanities GIS. This project brings together students and researchers to build a collaborative literary and historical open access atlas of Mary Shelley’s Frankenstein. As a pedagogical experiment, “A Frankenstein Atlas” helps teachers and students explore the rich spatial imaginary of Frankenstein⁠ while teaching students basic skills in digital humanities and literary and historical analysis. It highlights how the digital humanities can be employed effectively to teach students about the theoretical and methodological challenges inherent to text analysis and research, using both traditional and digital methodologies. The design of the project and its analytical approach provide a model for how other similar projects might be implemented in the classroom.</p>
  </div>

  <!-- Main Links Section -->
  <div class="w3-row-padding ">
    <div class="w3-col l3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-black w3-padding">Rationale and Methods</div>
        <a href="methods.html"><img src="https://6500jmk4.github.io/afrankensteinatlas/Images/gissample.jpg" alt="Rationale and Methods Icon" style="width:100%"></a>
      </div>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-black w3-padding">Maps and Gazetteer</div>
        <a href="maps.html"><img src="https://6500jmk4.github.io/afrankensteinatlas/Images/Racehorse_and_Carcass_forcing_thruogh_the_ice-square.jpg" alt="Racehorse ship" style="width:100%"></a> 
      </div>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-black w3-padding">Data Sets on Github</div>
        <a href="data.html"><img src="https://6500jmk4.github.io/afrankensteinatlas/Images/France_1789-1813-square.jpg" alt="Icon for Data Sets" style="width:100%"></a>
      </div>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-black w3-padding">Bibliography</div>
        <a href="bibliography"><img src="https://6500jmk4.github.io/afrankensteinatlas/Images/lackingtons-square.jpg" alt="Bibliography Icon" style="width:100%"></a>
      </div>
    </div>
  </div>

<!-- End page content -->
</div>


<!-- Footer -->
<footer class="w3-center w3-black w3-padding-16">
  <p>To cite this project, please use Kelly, Jason M., ed., "A Frankenstein Atlas" (2019). Accessed on [DATE].</p>
  <p>Contact</p>
  <p>Donate</p>
</footer>

</body>
</html>