<!DOCTYPE html>
<html>
<head>
<title>A Frankenstein Atlas Home</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<!-- Header Section -->
<?php include("header.php"); 
?>


<!-- About Section -->
<div class="w3-container w3-padding-32" id="About">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16"> About</h3>
    <p><em>A Frankenstein Atlas</em> explores Mary Shelley's novel <em>Frankenstein</em> from a spatial perspective. Inspired by research and theoretical approaches in literary mapping and historical geography, <em>A Frankenstein Atlas</em> provides scholars and students with a platform to study and experiment with Shelley's text.</p> 

    <p>This website provides users with access to the maps, gazetteer, pedagogical approach, and writing generated by the <em>Frankenstein Atlas </em> team. It also provides a link to the datasets and schemas underlying the atlas. Teachers are encouraged to create new maps as well as use, improve, and expand these data sets in their courses by creating Github branches. New work can then be integrated into the main repository and, through collaboration, this project can continue to expand.</p>
</div>


<!-- Contributors Section -->
<div class="w3-container w3-padding-32" id="Contributors">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16"> Contributors</h3>
    <p><em>A Frankenstein Atlas </em>was originally created as a class project for the course, "<a href="https://ageofmachines.wordpress.com/" target="_blank" rel="noopener">Machines and the Age of Invention</a>," taught by Jason M. Kelly during Spring 2018. Using <em>Frankenstein</em> as its key text, the course explored the history of science and medical ethics during the 18th and 19th centuries. Topics discussed in class included grave robbing, dissection, gender, and human consciousness. Students in the course worked collaboratively to develop the schema for our analysis as well as coding the text for integration and analysis using GIS. Students who participated in this project included Jessie Cortesi, Dalton Gackle, Patrick Hanlon, Kyla Lewis, Blake Miller, and Sam Opsahl. The schema, data sets, and website is edited by Jason M. Kelly.</p>
    
    <p>This project and the course “Machines in the Age of Invention” were developed as part of IUPUI’s commitment to <a href="https://indianahumanities.org/programs/one-state-one-story-frankenstein" target="_blank" rel="noopener">One State / One Story: Frankenstein</a>, an Indiana Humanities program made possible in part by a major grant from the National Endowment for the Humanities. Any views, findings, conclusions or recommendations expressed in this program do not necessarily represent those of the National Endowment for the Humanities.</p>
</div>


<!-- Using the Atlas Section -->
<div class="w3-container w3-padding-32" id="Using the Atlas">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Using the Atlas</h3>
    <p>Mary Shelley’s (née Godwin) Frankenstein is a profoundly geographical text. The novel opens with an epistolary exchange between St. Petersburg and London and, from there, it takes readers on a peregrination back-and-forth across Northern Europe and the circumpolar north. The book’s characters expand the text’s geographic boundaries by imagining lands and peoples in the Americas, Asia, and the Pacific. The ways in which Shelley describes these places is essential not only to the narrative but also to our understanding of the novel’s fundamental themes. Given this rich geographical framework, <em>Frankenstein</em> offers teachers a valuable tool with which to explore the historical, geographical, and literary worlds of the late eighteenth and early nineteenth centuries.</p>

    <p>An open access project created at IUPUI in 2017-2018 in response to the 200th anniversary of the book’s publication, <em>A Frankenstein Atlas</em> is deeply influenced by the theories and practices associated with the spatial humanities—especially literary mapping, deep mapping, and humanities GIS. This project brings together students and researchers to build a collaborative literary and historical open access atlas of Mary Shelley’s <em>Frankenstein</em>. As a pedagogical experiment, “A Frankenstein Atlas” helps teachers and students explore the rich spatial imaginary of <em>Frankenstein</em>⁠ while teaching students basic skills in digital humanities and literary and historical analysis. It highlights how the digital humanities can be employed effectively to teach students about the theoretical and methodological challenges inherent to text analysis and research, using both traditional and digital methodologies. The design of the project and its analytical approach provide a model for how other similar projects might be implemented in the classroom.</p>
    </div>

    

<!-- Coming Soon Section -->
<div class="w3-container w3-padding-32" id="Coming Soon">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Coming Soon</h3>
    <p>We are in the process of releasing additions to the atlas in the form of gazetteer entres and essays that work together to create a "deep map" that link to contemporary drawings and paintings, literary texts, and geophysical descriptions.</p>
     
     <p>Stay tuned for more details about the pedagogical framework of <em>A Frankenstein Atlas</em> which will be available in the forthcoming article, "A Frankenstein Atlas: A Spatial Humanities Framework for Teaching Frankenstein."</p>
</div>







<!-- Footer Section -->
<?php include("footer.php"); 
?>

<!-- End page content -->
</div>




</body>
</html>