<!DOCTYPE html>
<html>
<title>A Frankenstein Atlas Home</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<body>

<!-- BEGIN header.php INCLUDE -->
  <?php include("./header.php");
  ?>

<!-- Page content -->
<div class="w3-content w3-padding" style="max-width:1564px">

<!-- About Section -->
<div class="w3-container w3-padding-32" id="about">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">About</h3>
    <p>A Frankenstein Atlas explores Mary Shelley's novel Frankenstein from a spatial perspective. Inspired by research and theoretical approaches in literary mapping and historical geography, A Frankenstein Atlas provides scholars and students with a platform to study and experiment with Shelley's text.</p> 

    <p>This website provides users with access to the maps, gazetteer, pedagogical approach, and writing generated by the Frankenstein Atlas team. It also provides a link to the datasets and schemas underlying the atlas. Teachers are encouraged to create new maps as well as use, improve, and expand these data sets in their courses by creating Github branches. New work can then be integrated into the main repository and, through collaboration, this project can continue to expand. 
    </p>
  </div>


<!-- End page content -->
</div>


<!-- BEGIN footer.php INCLUDE -->
<?php include("./footer.php"); 
?>

</body>
</html>